package dk.au.cs.p2pn.india.reporting;

/**
 * Created by max on 20/02/14.
 */
public enum ReporterMeasurements {
	MESSAGE_RECEIVED,
	PING_SENT,
	NEIGHBOR_REQUEST_SENT,
	NEIGHBOR_REQUEST_RECEIVED,
	SEARCH_RECEIVED,
	SEARCH_PROCESSED,
	SEARCH_RESPONDED_SUCCESSFUL,
	SEARCH_STARTED,
	SEARCH_SUCCESSFUL,

}
